# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - 3.4
  - release
  - devel

before_install:
  - Rscript -e 'install.packages("mvtnorm")'

matrix:
  allow_failures:
    - r: devel

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

env:
  - _R_CHECK_SYSTEM_CLOCK_=0
