# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - release
  - devel

matrix:
  allow_failures:
    - r: devel

after_success:
  - Rscript -e 'covr::codecov(type = "all")'

env:
  - _R_CHECK_SYSTEM_CLOCK_=0
