# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

median_cpp <- function(x) {
    .Call('_adept_median_cpp', PACKAGE = 'adept', x)
}

pmax_max_cpp <- function(args) {
    .Call('_adept_pmax_max_cpp', PACKAGE = 'adept', args)
}

convolve_cpp <- function(a, b) {
    .Call('_adept_convolve_cpp', PACKAGE = 'adept', a, b)
}

sliding_cor_sd_cpp <- function(shortvec, longvec, sd_longvec_current) {
    .Call('_adept_sliding_cor_sd_cpp', PACKAGE = 'adept', shortvec, longvec, sd_longvec_current)
}

sliding_cor_store_sd_cpp <- function(shortvec, longvec) {
    .Call('_adept_sliding_cor_store_sd_cpp', PACKAGE = 'adept', shortvec, longvec)
}

